### ISSUE TITLE
Please consider adding an MPL2 LICENSE file.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/mp4parse_fallible#1]
Hi, I noticed that the sole source code object in this repository has an MPL2 abbreviated header. May I request that a LICENSE file be added with the complete MPL2 text in it? It’s not mandatory, but it’s significantly helpful when evaluating our licensing org-wide.

https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt

**Comment by rillian** [comment]
Done in 934d9b81c2e1b538144cc73851b73a5dead25b61. Thanks for the suggestion!
